### ISSUE TITLE
GUI multi-language support

### ISSUE THREAD

**Issue by wcxu21** [hermit99/nbrenamer#1]
Hi

Thank you for publishing this office software.

Could you consider adding multilingual support to it so that it can be used by more users.

Although there are not many settings on the interface, multiple languages can bring a better experience.

I am from China and I can provide you with Chinese translation.

Thanks for your work.：-D

**Comment by hermit99** [comment]
Thanks for your suggestion. Actually Internationalization is already in the roadmap.

It's held up at the moment as we may see the whole underlying libraries be swapped out in the next major release.

So please stay tuned :)

Cheers,
